### ISSUE TITLE
transcripts in fasta

### ISSUE THREAD

**Issue by rnjv** [bcgsc/ChopStitch#2]
How do I reconstruct a transcript fasta for all possible subgraphs? I assume you would need the DOT file, but I am unsure how to proceed from there on.

**Comment by hamzakhanvit** [comment]
Hi,

**Comment by hamzakhanvit** [comment]
Hi,

The primary output of ChopStitch is a FASTA file containing putative exons. The Splice subgraphs in the DOT file comprise of header names of these FASTA sequences. So you can select the headers of your subgraph of interest and extract the sequences from the putative exon FASTA file.

**Comment by rnjv** [comment]
Do you mean each sequence in the FASTA is a single exon?

If so, it will be useful to have a script which can extract all the super-transcripts with its exons concatenated and stored in a .fasta possibly having an accompanying .bed/.gff defining exon coordinates.

**Comment by hamzakhanvit** [comment]
Yes, each sequence in the FASTA is a single putative exon. 

Thank you, for the suggestion. We'll work on making a dot parsing script.
