### ISSUE TITLE
ccomps not accepting dot file from MakeSplicegraph.py

### ISSUE THREAD

**Issue by rnjv** [bcgsc/ChopStitch#3]
I get the following when I want to create subgraphs using ccomps

> Warning: splicegraph.dot:2: syntax error in line 2 near '.'

The command does not produce an output file.

**Comment by hamzakhanvit** [comment]
Did MakeSplicegraph.py ran fine? Can you show the first few lines of the dot file where it is showing a syntax error? Or could you share the dot file if its not huge?
